### ISSUE TITLE
How to open an Inventory to get it?

### ISSUE THREAD

**Issue by LOLYAYDEV** [HeronErin/McBotItPython#1]
How to open an Inventory to get it?

**Comment by LOLYAYDEV** [comment]
@HeronErin

**Comment by PsychedelicPalimpsest** [comment]
@LOLYAYDEV   You do not actually need to open the Inventory for manipulating the player's Inventory.  Here is an example of how to swap inventory slots from [examples/iceMine2.py](https://github.com/HeronErin/McBotItPython/blob/main/examples/iceMine2.py)
```python
playerinv = player.inventoryManager.getOpenPlayerInventory()
if playerinv.getSlot(0, 0)["durability"] < 100:

	slot1 = playerinv.getSlot(0, 0)["id"]
	for i in playerinv.items:
		if i["type"] == "minecraft:diamond_pickaxe":
			if i["durability"] > 100:
				player.swapSlots(i["id"], slot1, delay=0.1)
				time.sleep(1)
				break
```

Hope this helps, you are, to my knowledge, the only person other than myself to use this mod/tool. If you have any other questions, feel free to ask.

**Comment by LOLYAYDEV** [comment]
I am trying to swap with an item in a chest and i get the right ids: 2 and 36 but it just puts the item back in the chest

**Comment by LOLYAYDEV** [comment]
@HeronErin

**Comment by PsychedelicPalimpsest** [comment]
@LOLYAYDEV Sorry for the late reply.

I'm not too sure what the problem is, however just to be sure, the issue might be coming from using the wrong slot ids. You must get your ids from the chest class. Here is an example
```python
from mcbotit import Player, InputKeys
import time

player = Player(PORT)

# Open the chest
player.lookTowardBlock(x, y, z)
player.holdFor(InputKeys.RIGHT_CLICK,0.1)

# Some servers with large ping need time for the chest to load
time.sleep(5)

# Get the chest class. Throws AssertionError if chest GUI is not found
chest = player.inventoryManager.getOpenChest()

# Swap slots
player.swapSlots(chest.getSlot(row, col)["id"], chest.getSlot(row2, col2)["id"])
```

You can also verify the correct ids to use on [this wiki.vg page](https://wiki.vg/Inventory)

**Comment by LOLYAYDEV** [comment]
You dont understand. I want to get an Item From the chest into my inventory, @HeronErin

**Comment by PsychedelicPalimpsest** [comment]
The example i gave was to show what you normally do. You must make sure to use the correct slot ids by getting them from `chest.getSlot(row2, col2)["id"]`

**Comment by LOLYAYDEV** [comment]
Here is my code. I just want it to get the first shulker in a chest to the inventory slot

```
player = Player(14901) # Creates player instance
sleep(1)
playerinv = player.inventoryManager.getOpenPlayerInventory()
slot1 = playerinv.getSlot(0, 0)["id"]
print(slot1)
#---------------------------------------------
player.goto(130,182,-74)
player.lookTowardBlock(127,182,-73)
player.holdFor(mcbotit.InputKeys.RIGHT_CLICK)
z = []

inv = player.inventoryManager.getOpenChest().search("minecraft:shulker_box")
inventory = [inven for inven in inv]
player.swapSlots(slot1,inventory[0]["id"], delay=1)


player.kill()
```

**Comment by PsychedelicPalimpsest** [comment]
Your issue is that you are using the slotid from the players inventory. If you look on this [website](https://wiki.vg/Inventory) slot ids are different in the players inventory while nothing is open, and in a chest inventory.

**Comment by PsychedelicPalimpsest** [comment]
player.inventoryManager.getOpenChest().getSlot(0,0)

Is what you might want. Play around with it.

**Comment by LOLYAYDEV** [comment]
I still cant get it to Work. Cant you just give me like example code that will get the first item in a chest?

**Comment by LOLYAYDEV** [comment]
I just realized that the inventory is included in player.inventoryManager.getOpenChest()
